CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_tokens (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token_id VARCHAR(255) NOT NULL,
  access_token_id VARCHAR(255) NOT NULL,
  user_agent TEXT,
  ip VARCHAR(100),
  flow_ips TEXT,
  location JSONB,
  last_used_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_keys (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  algorithm VARCHAR(50) DEFAULT 'RS256',
  public_key TEXT NOT NULL,
  key_fingerprint VARCHAR(100),
  key_size INTEGER DEFAULT 2048,
  expires_at TIMESTAMP NULL,
  last_used_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS webhooks (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  key VARCHAR(255) NOT NULL,
  auth_key_id INTEGER REFERENCES auth_keys(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name, key)
);

CREATE TABLE IF NOT EXISTS webhook_logs (
  id SERIAL PRIMARY KEY,
  webhook_id INTEGER NOT NULL,
  method VARCHAR(50) NOT NULL,
  url TEXT NOT NULL,
  headers JSONB NOT NULL,
  query JSONB NOT NULL,
  body JSONB NOT NULL,
  ip VARCHAR(100),
  flow_ips TEXT,
  location JSONB,
  auth_status VARCHAR(50) DEFAULT 'none',
  response_status INTEGER DEFAULT 200,
  response_body TEXT DEFAULT 'ok',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE
);
